### ISSUE TITLE
[latest ] [ultimate] fullBright not Working [format work ] [ re -format]

### ISSUE THREAD

**Issue by robertoRollercoaster19** [Decyferable/Nivia-Client#10] opened 2017-03-31 17:29 UTC
--TENPLATE BEGIN--

![image](https://cloud.githubusercontent.com/assets/26822900/24561680/0b06870e-161e-11e7-9288-ac6dc629d772.png)

TENPLATE FOR FORMAT IS THERE.

iam running the latest version of pandora
iam verified pandora user
i have checked to make sure the bugs / issues 

--TENPLATE END--

HELO GUYS THIS IS MY SECOND POST WORK POST POSTING FULBRAIGHT GLITCH WHY IT GOT DELETED.
I BELIEVE IT WAS WHY OF THE FORMAT,, NOW FORMAT WORK AGAIN

PS: MY KEYBOARD IS BROKE SO SORRY FOR caps
THE ISSUE:
 ---FULLBRIGHT ISNT WORKING ON SPESIFIED MINECRAFT SERVERS OR POTION---

PLEASE FIX ASAP

**Comment by LouiseSan** [comment] 2017-03-31 17:31
This is a common problem if you have fast render on or a weird texturepack. Try changing your texturepack and report back.

**Comment by robertoRollercoaster19** [comment] 2017-03-31 17:35
OK SO I TRIED TO CHANGE MY RESOOURCE PACK THANKS FOR THIS RESPONSE AND FAST RESPONSE TIME TIMER BUT MY RESOSRE PACK I CHANGED AND NOW MY TEXTURES ARE BUG BECAUSE I USED STIMPY PACK BUT FULLBRIGHT IS STIL BUG :/ PLEASE HELP THIS IS REALLY IMPRTANT FOR MINERS LIKE ME

**Comment by inventor02** [comment] 2017-03-31 18:00
Thanks for getting in touch.

You'll need to provide some more info. What resource packs are enabled? What are your video settings?

Also, if you managed to type the template in lowercase you can type the rest in lowercase. Stop using all caps, it's just annoying to read.

~ George | UK Account Manager

**Comment by robertoRollercoaster19** [comment] 2017-03-31 18:02
YOU IS WRONG . MY KEYBOARD RANDOMLY BUGGED OUT SO U DONT KNOW HOW IS MY BRAIN OF MY KEYBOARD SO STOP LYEING LIAR  OK 

I HAD NONE RESOURCE PACKS AND CAVE NO RENDER RESOURCE PACK BUT FULBRIGHT NOT WORK ON ITI 🥇

**Comment by Decyferable** [comment] 2017-03-31 18:12
Try turning down your brightness in settings then turning it back up.

**Comment by MatthewSH** [comment] 2017-03-31 18:55
Please do not type in caps any longer. This entire issue is completely formatted wrong and I'm surprised anyone is dealing with it. From here on out, please communicate and type normally or we won't know if you're trolling and trying to spam up the issues and we'll close it.

**Comment by Pabsb** [comment] 2017-03-31 20:20
You did type in lower case with typing in caps first. You also can hold shift while caps is on to make it lower case. Please also use correct grammar otherwise we won't help you out as how it is to confusing to read and understand. Also please list the steps as it happens otherwise this is just a problem on your end which I believe 99% to be true.

**Comment by inventor02** [comment] 2017-04-03 16:03
No response in 3 days and the issue is formatted incorrectly. Closed.

**Closed as completed by inventor02** 2017-04-03 16:03 UTC
Labels: unconfirmed, invalid
